#! /bin/sh

### BEGIN INIT INFO
# Provides:          newlisp-fastcgi
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable newlisp fastcgi on port 9000
### END INIT INFO

case "$1" in
  start)
        echo -n "Starting newlisp fastcgi on port 9000 "
		start-stop-daemon --start --background  --exec /usr/bin/newlisp /root/working/newlisp-fastcgi/fastcgi.lsp
        echo "."
        ;;
  stop)
        echo -n "KILLALL newlisp"
		killall newlisp
        echo "."
        ;;

  *)
        echo "Usage: /sbin/service nvclock15 {start|stop}"
        exit 1
esac

exit 0


